project/models.py
from project import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    login_count = db.Column(db.Integer, unique=False, nullable=True)
    session_token = db.Column(db.String(40), index=True)

    def __repr__(self):
        return '<User %r>' % self.username

project/package/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired
from wtforms import widgets, SelectMultipleField

class MultiCheckboxField(SelectMultipleField):
    # widget = widgets.ListWidget(html_tag="ol", prefix_label=False)
    widget = widgets.TableWidget(with_table_tag=True)
    option_widget = widgets.CheckboxInput()

class NameForm(FlaskForm):
    # name = None # StringField('Which is your favorite place?', validators=[DataRequired()])
    SEQ_CHOICES = [('loadData', 'Load Data'), ('createplots', 'Create Plots')]
    SEQ_CHOICES.append(('fitEff', 'Fit efficiency distributions'))
    SEQ_CHOICES.append(('buildPdfs', 'Build PDF models'))
    SEQ_CHOICES.append(('fitSigM', 'Fit mass distribution (Signal)'))
    SEQ_CHOICES.append(('fitSigT', 'Fit decay time distribution (Signal)'))
    SEQ_CHOICES.append(('fitSigE', 'Fit decay time-error distribution (Signal)'))
    SEQ_CHOICES.append(('fitPeakM', 'Fit peaking mass distribution (Signal)'))
    SEQ_CHOICES.append(('fitPeakT', 'Fit peaking decay time distribution (Signal)'))
    seqKey = SelectField(u'Choose sequence to execute', default='buildPdfs', choices=SEQ_CHOICES)
    year = SelectField(u'Choose year of the data taking', choices=[2016, 2017, 2018], validators=[DataRequired()])
    plot_choices = [('plot_sigEfficiency', 'Signal efficiency distributions')]
    plot_choices += [('plot_peakEfficiency', 'Peak efficiency distribution'), ('plot_sigM', 'Bmass fit')]
    plot_choices += [('plot_sigT', 'Decay time distribution'), ('plot_sigE', 'Decay time Error')]
    plot_list = MultiCheckboxField('Select multiple options to plot the distributions', choices=plot_choices)
    # sequences = MultiCheckboxField('Label', choices=[('Choice1', 'Choice1'), ('Choice2', 'Choice2'), ('Choice3', 'Choice3')])
    submit = SubmitField('Submit')

project/__init__.py
from flask import Flask, redirect, session, flash, request
from authlib.integrations.flask_client import OAuth
from authlib.jose import jwt
import json, jsonify
from flask import url_for, render_template
from flask_sqlalchemy import SQLAlchemy
import os, ast
from flask_bootstrap import Bootstrap

# Based on the official Authlib example for Google:
# https://github.com/authlib/demo-oauth-client/blob/master/flask-google-login/app.py

app = Flask(__name__)

# app.config.from_pyfile("app.cfg")
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///userbase.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['CUSTOM_STATIC_PATH'] = 'userfiles/'
db = SQLAlchemy(app)

from project.auth.views import auth_blueprint
from project.package.views import fitter_blueprint
app.register_blueprint(auth_blueprint)
app.register_blueprint(fitter_blueprint, url_prefix='/fitter')

Bootstrap(app)
app.secret_key = os.urandom(24)

@app.route('/')
def root():
	return redirect(url_for('auth.index'))

project/package/views.py
import os, jsonify, glob, pdb
from flask import Blueprint, render_template, session, url_for, redirect, request, flash, g
from flask import send_from_directory, send_file, Response, stream_with_context
from werkzeug.security import safe_join
from .forms import NameForm
from functools import wraps
from shelljob import proc
from project.models import User
from project import db
from project import app

fitter_blueprint = Blueprint(
	'fitter',
	__name__,
	template_folder='templates',
	static_folder='static'
	)

from project.auth.views import oidc, login_required

gobal_process = proc.Group()

@fitter_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
	print(request.headers.get('User-Agent'))
	form = NameForm()
	if form.validate_on_submit() or request.method == 'POST':
		data = form.plot_list.data
		flash("Executing the sequence that you provided!")
		execute_sequences(form.data, plotsPath=session['USERFILES_PATH'])
	files = get_files()
	return render_template('index.html', user_name=session['USER_NAME'], form=form, files=files, proc=gobal_process)

def execute_sequences(form, plotsPath = None):
	form.pop('submit')
	form.pop('csrf_token')
	print(form)
	plot_list = ["effi"] if len(form['plot_list'])==0 else (" ").join(form['plot_list'])
	path = safe_join(app.root_path, 'package/fitter/LifetimeFitter/')
	cmd_list = [ "bash", "-c", "cd %s; python3 -u seqCollection.py"%path ]
	cmd_list[-1] += " -s %s" % form['seqKey']
	cmd_list[-1] += " --list %s" % (plot_list)
	cmd_list[-1] += " -y %s" % form['year']
	cmd_list[-1] += f" --pp {plotsPath}"
	cmd_list[-1] += "; cd -"
	print(cmd_list)
	# cmd_list = [ "bash", "-c", "for ((i=0;i<30;i=i+1)); do echo $i; sleep 1; done" ]
	p = gobal_process.run( cmd_list )

@fitter_blueprint.route('/plots')
@login_required
def plots():
	files = get_files()
	return render_template('plots.html', user_name=session['USER_NAME'], files=files)

@fitter_blueprint.route('/show/<path:filename>')
@login_required
def show_image(filename):
	return send_from_directory(session['USERFILES_PATH'], filename)

def get_files():
	os.chdir(session['USERFILES_PATH'])
	data = dict()
	for year in ['2016', '2017', '2018']:
		data[year] = dict()
		data[year]['Efficiency'] = glob.glob(f'plots_{year}/Efficiency/*.png')
		data[year]['SignalFits'] = glob.glob(f'plots_{year}/SignalFits/*.png')
	return data

# @fitter_blueprint.route( '/stream' )
# @login_required
# def stream():
# 	def read_process():
# 	    while gobal_process.is_pending():
# 		    lines = gobal_process.readlines()
# 		    for proc, line in lines:
# 			    yield line
# 	return Response( read_process(), mimetype= 'text/plain' )

# import eventlet
# eventlet.monkey_patch()

@fitter_blueprint.route( '/stream' )
def stream():
  def read_process():
    while gobal_process.is_pending():   
      lines = gobal_process.readlines()
      for proc, line in lines:
        yield "data:"+line.decode('UTF-8')+"\n\n"
  return Response( read_process(), mimetype= 'text/event-stream' )

@fitter_blueprint.route('/page')
def get_page():
    return render_template('page.html')

project/templates/base.html
<!DOCTYPE html>                                                                                                                                       
<html lang="en">                                                                
    <head>                                                                      
        <meta charset="utf-8" />                                                
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />                                  
        <meta name="author" content="" />                                       
        <title>Fitter</title>                                          
        <!-- Favicon-->
        <!-- <link rel="shortcut icon" href="#"> -->
        <link rel="shortcut icon" href="https://github.com/fluidicon.png" title="GitHub">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <!-- Font Awesome CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
                crossorigin="anonymous"> </script>
        <script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>

        {% block headercontent %} {% endblock %}
    </head>
    <body>
        <!-- Responsive navbar-->                                               
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="box-shadow: 0px 5px 5px -5px gray;">
          <a class="navbar-brand" href="{{ url_for('auth.index')}}"><strong>Angular</strong>Fitter</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('fitter.index') }}">Lifetime Fitter</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('fitter.plots') }}">Plots</a>
              </li>
            </ul>
            <ul class="navbar-nav navbar-right">
              {% block nav_buttons %}
                <li class="nav-item active"><a class="nav-link" href="{{ url_for('auth.login') }}"><span class="fa fa-user-o"></span> Login</a></li>
              {% endblock %}
            </ul>
          </div>
        </nav>

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{message}}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}
        {% endblock %}
    </body>                                                                     
</html>