project/package/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired
from wtforms import widgets, SelectMultipleField

class MultiCheckboxField(SelectMultipleField):
    # widget = widgets.ListWidget(html_tag="ol", prefix_label=False)
    widget = widgets.TableWidget(with_table_tag=True)
    option_widget = widgets.CheckboxInput()

class NameForm(FlaskForm):
    # name = None # StringField('Which is your favorite place?', validators=[DataRequired()])
    SEQ_CHOICES = [('loadData', 'Load Data'), ('createplots', 'Create Plots')]
    SEQ_CHOICES.append(('fitEff', 'Fit efficiency distributions'))
    SEQ_CHOICES.append(('buildPdfs', 'Build PDF models'))
    SEQ_CHOICES.append(('fitSigM', 'Fit mass distribution (Signal)'))
    SEQ_CHOICES.append(('fitSigT', 'Fit decay time distribution (Signal)'))
    SEQ_CHOICES.append(('fitSigE', 'Fit decay time-error distribution (Signal)'))
    SEQ_CHOICES.append(('fitPeakM', 'Fit peaking mass distribution (Signal)'))
    SEQ_CHOICES.append(('fitPeakT', 'Fit peaking decay time distribution (Signal)'))
    seqKey = SelectField(u'Choose sequence to execute', default='buildPdfs', choices=SEQ_CHOICES)
    year = SelectField(u'Choose year of the data taking', choices=[2016, 2017, 2018], validators=[DataRequired()])
    plot_choices = [('plot_sigEfficiency', 'Signal efficiency distributions')]
    plot_choices += [('plot_peakEfficiency', 'Peak efficiency distribution'), ('plot_sigM', 'Bmass fit')]
    plot_choices += [('plot_sigT', 'Decay time distribution'), ('plot_sigE', 'Decay time Error')]
    plot_list = MultiCheckboxField('Select multiple options to plot the distributions', choices=plot_choices)
    # sequences = MultiCheckboxField('Label', choices=[('Choice1', 'Choice1'), ('Choice2', 'Choice2'), ('Choice3', 'Choice3')])
    submit = SubmitField('Submit')

project/package/views.py
import os, jsonify, glob, pdb
from flask import Blueprint, render_template, session, url_for, redirect, request, flash, g
from flask import send_from_directory, send_file, Response, stream_with_context
from werkzeug.security import safe_join
from .forms import NameForm
from functools import wraps
from shelljob import proc
from project.models import User
from project import db
from project import app

fitter_blueprint = Blueprint(
	'fitter',
	__name__,
	template_folder='templates',
	static_folder='static'
	)

from project.auth.views import oidc, login_required

gobal_process = proc.Group()

@fitter_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
	print(request.headers.get('User-Agent'))
	form = NameForm()
	if form.validate_on_submit() or request.method == 'POST':
		data = form.plot_list.data
		flash("Executing the sequence that you provided!")
		execute_sequences(form.data, plotsPath=session['USERFILES_PATH'])
	files = get_files()
	return render_template('index.html', user_name=session['USER_NAME'], form=form, files=files, proc=gobal_process)

def execute_sequences(form, plotsPath = None):
	form.pop('submit')
	form.pop('csrf_token')
	print(form)
	plot_list = ["effi"] if len(form['plot_list'])==0 else (" ").join(form['plot_list'])
	path = safe_join(app.root_path, 'package/fitter/LifetimeFitter/')
	cmd_list = [ "bash", "-c", "cd %s; python3 -u seqCollection.py"%path ]
	cmd_list[-1] += " -s %s" % form['seqKey']
	cmd_list[-1] += " --list %s" % (plot_list)
	cmd_list[-1] += " -y %s" % form['year']
	cmd_list[-1] += f" --pp {plotsPath}"
	cmd_list[-1] += "; cd -"
	print(cmd_list)
	# cmd_list = [ "bash", "-c", "for ((i=0;i<30;i=i+1)); do echo $i; sleep 1; done" ]
	p = gobal_process.run( cmd_list )

@fitter_blueprint.route('/plots')
@login_required
def plots():
	files = get_files()
	return render_template('plots.html', user_name=session['USER_NAME'], files=files)

@fitter_blueprint.route('/show/<path:filename>')
@login_required
def show_image(filename):
	return send_from_directory(session['USERFILES_PATH'], filename)

def get_files():
	os.chdir(session['USERFILES_PATH'])
	data = dict()
	for year in ['2016', '2017', '2018']:
		data[year] = dict()
		data[year]['Efficiency'] = glob.glob(f'plots_{year}/Efficiency/*.png')
		data[year]['SignalFits'] = glob.glob(f'plots_{year}/SignalFits/*.png')
	return data

# @fitter_blueprint.route( '/stream' )
# @login_required
# def stream():
# 	def read_process():
# 	    while gobal_process.is_pending():
# 		    lines = gobal_process.readlines()
# 		    for proc, line in lines:
# 			    yield line
# 	return Response( read_process(), mimetype= 'text/plain' )

# import eventlet
# eventlet.monkey_patch()

@fitter_blueprint.route( '/stream' )
def stream():
  def read_process():
    while gobal_process.is_pending():   
      lines = gobal_process.readlines()
      for proc, line in lines:
        yield "data:"+line.decode('UTF-8')+"\n\n"
  return Response( read_process(), mimetype= 'text/event-stream' )

@fitter_blueprint.route('/page')
def get_page():
    return render_template('page.html')

project/package/templates/index.html
{% extends 'base.html' %}
{% block headercontent %}
    <link href="{{ url_for('fitter.static', filename='styles.css') }}" rel="stylesheet" />
    <script src="{{ url_for('fitter.static', filename='js/script.js') }}" type="text/javascript"></script>
{% endblock %}

{% block nav_buttons %}
	{% if user_name %}
	  <li class="nav-item active"><a class="nav-link"><font face="Courier"><small>Logged in as</small> {{user_name}}&nbsp;</font></a></li>
	  <li class="nav-item active"><a class="nav-link" href="{{ url_for('auth.logout') }}"><span class="fa fa-user-o"></span> Sign Out</a></li>
	{% else %}
		<li class="nav-item active"><a class="nav-link" href="{{ url_for('auth.login') }}"><span class="fa fa-user-o"></span> Login</a></li>
	{% endif %}
{% endblock %}

{% block content %}
<form method="POST" style='text-align: left; margin: 5px; padding: 10px 20%;'>
    {{ form.hidden_tag() }}
    <div class="form-group">
    	{{ form.seqKey.label }} {{ form.seqKey(class="form-control") }} 
		</div>

		<div id="plot-checklist">
	    {{ form.plot_list.label }}
	    <div class="form-group">
		    {% for seq in form.plot_list %} 
			    <div class="form-check form-check-inline">
				    	{{seq(class="form-check-input")}}{{seq.label(class="form-check-label")}}
			    </div>
		    {% endfor %}
	  	</div>
		</div>

    <div class="form-group">
    	{{ form.year.label }} {{ form.year(class="form-control") }} 
    </div>

    <div style="text-align: center;">
	    {{ form.submit(class_="btn btn-primary") }}
	</div>
</form>

{% if proc.is_pending() %}
	<button class="reveal btn btn-outline-dark" style="margin: 5px;" onclick="toggle_display('embed_section_id')">Hide <i class="fa fa-chevron-circle-up"></i></button>
	<div id="embed_section_id"><embed src="page" width="100%" height="300px"/></div>
{% endif %}


{% endblock %}

project/package/templates/page.html
<!DOCTYPE html>
<html>
<head>
    <script>
    var source = new EventSource("/fitter/stream");
    source.onmessage = function(event) {
        document.getElementById("output").innerHTML += event.data + "<br/>"
    }
    </script>
</head>
<body>
    <pre id="output"></pre>
</body>
</html>

project/package/templates/plots.html
{% extends 'base.html' %}
{% block headercontent %}
    <link href="{{ url_for('fitter.static', filename='styles.css') }}" rel="stylesheet" />
    <script src="{{ url_for('fitter.static', filename='js/script.js') }}" type="text/javascript"></script>
{% endblock %}

{% block nav_buttons %}
	{% if user_name %}
	  <li class="nav-item active"><a class="nav-link"><font face="Courier"><small>Logged in as</small> {{user_name}}&nbsp;</font></a></li>
	  <li class="nav-item active"><a class="nav-link" href="{{ url_for('auth.logout') }}"><span class="fa fa-user-o"></span> Sign Out</a></li>
	{% else %}
		<li class="nav-item active"><a class="nav-link" href="{{ url_for('auth.login') }}"><span class="fa fa-user-o"></span> Login</a></li>
	{% endif %}
{% endblock %}

{% block content %}

<div class="plot-box"><button class="btn btn-secondary" id="expand-collapse">Expand all <i class="fa fa-chevron-circle-down"></i></button></div>
<div class=plot-box>
	<button class="reveal btn btn-secondary" onclick="toggle_display('eff_plots')">Show <i class="fa fa-chevron-circle-down"></i></button> Efficiency Plots 
	{% if files %}
		<div class="content_section" id="eff_plots" style="display: none; margin: 5px;">
			{% for year, effi_files in files.items() %}
				{% for filename in effi_files['Efficiency'] %}
					{% set url = url_for('fitter.show_image', filename=filename) %}
					<a href="{{ url }}" target="_blank" rel="noopener noreferrer"><img src="{{ url }}" width="24.5%"/><a/>
				{% endfor %}
			{% endfor %}
		</div>
	{% endif %}
</div>


<div class=plot-box>
	<button class="reveal btn btn-secondary" onclick="toggle_display('sig_plots')">Show <i class="fa fa-chevron-circle-down"></i></button> Signal Plots
	{% if files %}
		<div class="content_section" id="sig_plots" style="display: none; margin: 5px;">
			{% for year, effi_files in files.items() %}
				{% for filename in effi_files['SignalFits'] %}
					{% set url = url_for('fitter.show_image', filename=filename) %}
					<a href="{{ url }}" target="_blank" rel="noopener noreferrer"><img src="{{ url }}" width="24.5%"/><a/>
				{% endfor %}
			{% endfor %}
		</div>
	{% endif %}
</div>

{% endblock %}